#!/usr/bin/env bash
# Regenerate CONTRIBUTORS.md from GitHub contributor data.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

REPO="${1:-$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || true)}"
if [ -z "$REPO" ]; then
  echo "Usage: $0 [owner/repo]" >&2
  exit 1
fi

REPO_NAME="${REPO##*/}"
OUT="$ROOT/CONTRIBUTORS.md"
GRAPH_URL="https://github.com/$REPO/graphs/contributors"

rows="$(
  gh api "repos/$REPO/contributors" --paginate 2>/dev/null | jq -r '
    .[]
    | select(.type != "Bot")
    | select(.login != "github-actions[bot]")
    | "\(.login)|\(.contributions)"
  ' | while IFS='|' read -r login contributions; do
    name="$(gh api "users/$login" --jq '.name // empty' 2>/dev/null || true)"
    if [ -z "$name" ] || [ "$name" = "null" ]; then
      name="$login"
    fi
    role="Contributor"
    owner="$(gh repo view "$REPO" --json owner -q .owner.login 2>/dev/null || true)"
    if [ "$login" = "$owner" ]; then
      role="Creator & maintainer"
    fi
    printf '| %s | [@%s](https://github.com/%s) | %s | %s |\n' "$name" "$login" "$login" "$role" "$contributions"
  done
)"

if [ -z "${rows//[[:space:]]/}" ]; then
  owner="$(gh repo view "$REPO" --json owner -q .owner.login)"
  name="$(gh api "users/$owner" --jq '.name // .login')"
  rows="| $name | [@$owner](https://github.com/$owner) | Creator & maintainer | — |"
fi

{
  cat <<EOF
# Contributors

Thank you to everyone who helps improve **$REPO_NAME**.

| Name | GitHub | Role | Commits |
|------|--------|------|---------|
$rows

## Attribution

- Full commit history: [$REPO contributors graph]($GRAPH_URL)
- To contribute: [CONTRIBUTING.md](./CONTRIBUTING.md) · [good first issues](docs/good-first-issues.md)

---

*This file is generated by \`pnpm contributors:update\`. After your first merged PR, ask a maintainer to refresh the list or run the script yourself.*
EOF
} >"$OUT"

echo "Wrote $OUT"